### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by travispaul** [peachananr/loading-bar#2]
What is the license for this jQuery Plugin?

Thanks!

**Comment by pklink** [comment]
+1

**Comment by tOkeshu** [comment]
+1

**Comment by andrewwakeling** [comment]
+1

**Comment by travispaul** [comment]
I'm not sure why @peachananr hasn't responded but I gave up waiting  on  a response long ago and just implemented my own for my specific need.

**Comment by jtfairbank** [comment]
+1 @TravisPaul can you link to yours?

**Comment by nathanhornby** [comment]
@TravisPaul If no license is included with GitHub projects (either in the readme or license file) then by default it is a standard Copyright license (it doesn't default to 'no license'). So be careful with that.

From [GitHub help](https://help.github.com/articles/open-source-licensing/):

> What happens if I don't choose a license?
> 
> You're under no obligation to choose a license. It's your right not to include one with your code or project, but please be aware of the implications. Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.
> 
> Even if this is what you intend, if you publish your source code in a public repository on GitHub, you have accepted the Terms of Service which do allow other GitHub users some rights. Specifically, you allow others to view and fork your repository.
> 
> If you want to share your work with others, we strongly encourage you to include an open source license.

However It does state in the `README.md` that it uses an [Attribution-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/deed.en_US) license :)

This license was added after the initial question was asked though! So more relevant for @jtfairbank

**Comment by peachananr** [comment]
You can use however you like! Credit is appreciated but not compulsory. :)
