### ISSUE TITLE
Website navigation

### ISSUE THREAD

**Issue by suriyaa** [peachananr/loading-bar#5]
Hi Pete, :smile:

I tired to use your loading bar for my **website navigation**. But it can't redirect it to a spezific site.
Where is the problem?
- Source: https://github.com/iSC-Host/suriyaa.me/blob/gh-pages/_includes/header.html
- Website: http://isc-host.github.io/suriyaa.me/

I hope you can help me.

Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by SuriyaaKudoIsc** [comment]
@peachanar

**Comment by suriyaa** [comment]
@peachananr

**Comment by suriyaa** [comment]
Removed this project on my website because nobody helped me out on this issue. I'm going to close this issue.
